[package]
name = "cli-quick-replace"
version = "0.1.0"
authors = ["Fernando Cejas <android10@fernandocejas.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
text-colorizer = "1.0.0"
regex = "1.7.0"